### ISSUE TITLE
* reports no connectivity to the internet. 

### ISSUE THREAD

**Issue by napswastaken** [simeononsecurity/Standalone-Windows-Server-STIG-Script#1]
Edition	Windows 11 Home
Version	22H2
Installed on	‎11/‎9/‎2022
OS build	22621.525
Experience	Windows Feature Experience Pack 1000.22634.1000.0

After running this script, couple internet based issues

The Network List Manager reports no connectivity to the internet.
A connection to the Windows Update service could not be established.
The Network List Manager reports no connectivity to the internet.
A connection to the Windows Metadata and Internet Services (WMIS) could not be established.
The Network List Manager reports no connectivity to the internet.
The Network List Manager reports no connectivity to the internet.
A connection to the Windows Update service could not be established.
The Network List Manager reports no connectivity to the internet.

Errors occur with programs which reach out to an endpoint such as Bitwarden, Nvidia Broadcast and more say there is no internet connection.

Didn't know I was on windows 11 home when i installed this version but thought i'd report the issues regardless

**Comment by simeononsecurity** [comment]
This script is clearly for Windows Servers and not Windows 11 desktops. 
Perhaps you meant one of the other repos?

Additionally, many of those programs are in our testing. We've confirmed again against all of our repos and were unable to recreate the issue. But unfortunately, again, none of the home additions are supported. Since it isn't supported, all issues for it are not valid. Please create a discussion rather than a issue in the future. Thanks!
